#!/bin/bash

export PYTHONPATH=${PWD}
export FLASK_APP=src
export FLASK_ENV=development

if [[ "$VIRTUAL_ENV" == "" ]];then
    python3 -m venv venv
    . venv/bin/activate
    pip3 install -r requirements.txt
fi

flask run
